spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified&reWriteBatchedInserts=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_schema: bobo_short_url
        generate_statistics: false
        jdbc:
          batch_size: 100
        order_updates: true
        order_inserts: true
  flyway:
    enabled: true